name: chat_reaction_animation
description: A chat interface with reaction animations
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/emojis/
  
  fonts:
    - family: Druk
      fonts:
        - asset: assets/fonts/DrukWide-Bold-Trial.otf
          weight: 700